### ISSUE TITLE
Creating a Responsive Footer

### ISSUE THREAD

**Issue by johnsnel24** [Code-Institute-Solutions/AI-Augmented-Bootcamp#25]
**User Story**

As a website visitor, I want to see the footer with social media links and copyright information so that I can easily connect with the spa on social media and know the ownership details.

**Acceptance Criteria**

- [ ] The footer is displayed at the bottom of the page and includes social media icons and copyright text.
- [ ] The social media links in the footer open in a new tab.

**Tasks**

- [ ] Add a footer that includes social media links and copyright information.
- [ ] Ensure the social media links open in a new tab.
